server:
  port: 10392

spring:
  application:
    name: order-payment-service
  config:
    import: "optional:configserver:http://config-server:10394/"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: 220.67.216.14
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 320
management:
  health:
    rabbit:
      enabled: false

eureka:
  client:
    enabled: false

feign:
  client:
    book-service:
      api:
        url: http://localhost:10390
    coupon-service:
      api:
        url: http://localhost:10388

toss:
  payments:
    secretKey: test_sk_24xLea5zVAz14nAv17p0rQAMYNwW