### 도서 주문 유효성 검증 요청 (테스트 완료)
POST http://localhost:8082/api/books/validation/primary
Content-Type: application/json

{
  "orderItems": [
    {
      "bookId": 1,
      "quantity": 5
    },
    {
      "bookId": 2,
      "quantity": 10
    },
    {
      "bookId": 3,
      "quantity": 1
    }
  ]
}
